const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', //679 * 829
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
      owner: 1,
      store: 1,
      visible: 0,
    },
    {
      _id: '2',
      name: 'Addidas Fit Shirt',
      slug: 'addidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 100,
      brand: 'addidas',
      rating: 3,
      numReviews: 120,
      description: 'high quality shirt',
      owner: 1,
      store: 1,
      visible: 0,
    },
    {
      _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 18,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 12,
      description: 'high quality shirt',
      owner: 1,
      store: 1,
      visible: 0,
    },
    {
      _id: '4',
      name: 'Addidas Slim Pant',
      slug: 'addidas-slim-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 50,
      countInStock: 7,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 5,
      description: 'high quality shirt',
      owner: 1,
      store: 1,
      visible: 0,
    },
    {
      _id: '5',
      name: 'MS Woman Shoes',
      slug: 'MS-Woman-Shoes-23111',
      category: 'Shoes',
      image: '/images/s1.jpg', //679 * 829
      price: 20000,
      countInStock: 8,
      brand: 'MS',
      rating: 4.5,
      numReviews: 5,
      description: 'high quality shirt',
      owner: 1,
      store: 2,
      visible: 1,
    },
    {
      _id: '6',
      name: 'MS Woman Shoes',
      slug: 'MS-Woman-Shoes-23111',
      category: 'Shoes',
      image: '/images/s1.jpg', //679 * 829
      price: 20000,
      countInStock: 8,
      brand: 'MS',
      rating: 3,
      numReviews: 18,
      description: 'high quality shirt',
      owner: 1,
      store: 2,
      visible: 1,
    },
    {
      _id: '7',
      name: 'MS Woman Shoes',
      slug: 'MS-Woman-Shoes-23112',
      category: 'Shoes',
      image: '/images/s2.jpg', //679 * 829
      price: 20000,
      countInStock: 8,
      brand: 'MS',
      rating: 4.5,
      numReviews: 12,
      description: 'high quality shirt',
      owner: 1,
      store: 2,
      visible: 1,
    },
    {
      _id: '8',
      name: 'MS Woman Shoes',
      slug: 'MS-Woman-Shoes-23113',
      category: 'Shoes',
      image: '/images/s3.jpg', //679 * 829
      price: 20000,
      countInStock: 8,
      brand: 'MS',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality shirt',
      owner: 1,
      store: 2,
      visible: 1,
    },
    {
      _id: '9',
      name: 'MS Woman Shoes',
      slug: 'MS-Woman-Shoes-23114',
      category: 'Shoes',
      image: '/images/s4.jpg', //679 * 829
      price: 20000,
      countInStock: 8,
      brand: 'MS',
      rating: 2,
      numReviews: 10,
      description: 'high quality shirt',
      owner: 1,
      store: 2,
      visible: 1,
    },
    {
      _id: '10',
      name: 'MS Woman Shoes',
      slug: 'MS-Woman-Shoes-23115',
      category: 'Shoes',
      image: '/images/s5.jpg', //679 * 829
      price: 20000,
      countInStock: 0,
      brand: 'MS',
      rating: 2.5,
      numReviews: 10,
      description: 'high quality shirt',
      owner: 1,
      store: 2,
      visible: 1,
    },
  ],
};
export default data;
